#!/usr/bin/env python3
"""
curated_batch_2.py — Hand-curated wazn batch for Al-Baqarah 2:11–2:20.

Each entry verified against:
  (1) Quranic Arabic Corpus feature tags (mustafa0x/quran-morphology v0.4)
  (2) Classical sarf patterns (Form I-X, broken plurals, verbal nouns)

Tuple format: (wazn, wazn_form, wazn_meaning, root_in_template, wazn_examples)
'-' as wazn marks a non-derivable word (proper noun / particle / VN-as-null).
"""

CURATED_B2 = {
    # ── 2:11 ──────────────────────────────────────────────────────────────
    '2:11:2': ('فُعِلَ','Form I perfect passive verb','It was said — passive base verb','ق-و-ل → قِيلَ',
               [('كُتِبَ','root ك-ت-ب','it was written'),('فُتِحَ','root ف-ت-ح','it was opened')]),
    '2:11:5': ('يُفْعِلُ','Form IV imperfect verb','You corrupt — causative imperfect','ف-س-د → تُفْسِدُ',
               [('تُخْرِجُ','root خ-ر-ج','you bring out'),('تُنْزِلُ','root ن-ز-ل','you send down')]),
    '2:11:7': ('فَعْل','Form I noun','The earth — basic noun','أ-ر-ض → أَرْض',
               [('بَحْر','root ب-ح-ر','sea'),('أَمْر','root أ-م-ر','command')]),
    '2:11:8': ('فَعَلَ','Form I perfect verb (hollow)','They said — base perfect','ق-و-ل → قَالَ',
               [('كَانَ','root ك-و-ن','he was'),('زَادَ','root ز-ي-د','he increased')]),
    '2:11:11': ('مُفْعِل','Form IV active participle','Those who reform — causative doers','ص-ل-ح → مُصْلِح',
                [('مُحْسِن','root ح-س-ن','one who does good'),('مُكْرِم','root ك-ر-م','one who honors')]),
    # ── 2:12 ──────────────────────────────────────────────────────────────
    '2:12:4': ('مُفْعِل','Form IV active participle','Those who corrupt — causative doers','ف-س-د → مُفْسِد',
               [('مُحْسِن','root ح-س-ن','one who does good'),('مُكْرِم','root ك-ر-م','one who honors')]),
    '2:12:7': ('يَفْعُلُ','Form I imperfect verb','They perceive — base imperfect','ش-ع-ر → يَشْعُرُ',
               [('يَقُولُ','root ق-و-ل','he says'),('يَخْرُجُ','root خ-ر-ج','he goes out')]),
    # ── 2:13 ──────────────────────────────────────────────────────────────
    '2:13:2': ('فُعِلَ','Form I perfect passive verb','It was said — passive base verb','ق-و-ل → قِيلَ',
               [('كُتِبَ','root ك-ت-ب','it was written'),('فُتِحَ','root ف-ت-ح','it was opened')]),
    '2:13:4': ('أَفْعِلْ','Form IV imperative verb','Believe! — command form','أ-م-ن → آمِنْ',
               [('أَكْرِمْ','root ك-ر-م','honor!'),('أَنْزِلْ','root ن-ز-ل','send down!')]),
    '2:13:6': ('أَفْعَلَ','Form IV perfect verb','He believed — causative perfect','أ-م-ن → آمَنَ',
               [('أَنْزَلَ','root ن-ز-ل','he sent down'),('أَكْرَمَ','root ك-ر-م','he honored')]),
    '2:13:7': ('فَعَال','Form I noun (qur\'anic)','The people — from the root of sociability','أ-ن-س → نَاس',
               [('سَلَام','root س-ل-م','peace'),('جَمَال','root ج-م-ل','beauty')]),
    '2:13:8': ('فَعَلَ','Form I perfect verb (hollow)','They said — base perfect','ق-و-ل → قَالَ',
               [('كَانَ','root ك-و-ن','he was'),('زَادَ','root ز-ي-د','he increased')]),
    '2:13:9': ('يُفْعِلُ','Form IV imperfect verb','Do we believe? — causative imperfect','أ-م-ن → نُؤْمِنُ',
               [('نُكْرِمُ','root ك-ر-م','we honor'),('نُنْزِلُ','root ن-ز-ل','we send down')]),
    '2:13:11': ('أَفْعَلَ','Form IV perfect verb','He believed — causative perfect','أ-م-ن → آمَنَ',
                [('أَنْزَلَ','root ن-ز-ل','he sent down'),('أَكْرَمَ','root ك-ر-م','he honored')]),
    '2:13:12': ('فُعَلَاء','Broken plural','The fools — broken plural of سَفِيه','س-ف-ه → سُفَهَاء',
                [('عُلَمَاء','root ع-ل-م','scholars'),('أَنْبِيَاء','root ن-ب-أ','prophets')]),
    '2:13:16': ('فُعَلَاء','Broken plural','The fools — broken plural of سَفِيه','س-ف-ه → سُفَهَاء',
                [('عُلَمَاء','root ع-ل-م','scholars'),('أَنْبِيَاء','root ن-ب-أ','prophets')]),
    '2:13:19': ('يَفْعَلُ','Form I imperfect verb','They know — base imperfect','ع-ل-م → يَعْلَمُ',
                [('يَكْتُبُ','root ك-ت-ب','he writes'),('يَفْتَحُ','root ف-ت-ح','he opens')]),
    # ── 2:14 ──────────────────────────────────────────────────────────────
    '2:14:2': ('فَعِلَ','Form I perfect verb (kasra)','They met — base perfect','ل-ق-ي → لَقِيَ',
               [('رَضِيَ','root ر-ض-ي','he was pleased'),('نَسِيَ','root ن-س-ي','he forgot')]),
    '2:14:4': ('أَفْعَلَ','Form IV perfect verb','They believed — causative perfect','أ-م-ن → آمَنُوا',
               [('أَنْزَلُوا','root ن-ز-ل','they sent down'),('أَحْسَنُوا','root ح-س-ن','they did good')]),
    '2:14:5': ('فَعَلَ','Form I perfect verb (hollow)','They said — base perfect','ق-و-ل → قَالَ',
               [('كَانَ','root ك-و-ن','he was'),('زَادَ','root ز-ي-د','he increased')]),
    '2:14:6': ('أَفْعَلَ','Form IV perfect verb','We believed — causative perfect','أ-م-ن → آمَنَّا',
               [('أَنْزَلْنَا','root ن-ز-ل','we sent down'),('أَكْرَمْنَا','root ك-ر-م','we honored')]),
    '2:14:8': ('فَعَلَ','Form I perfect verb (defective)','They withdrew — base perfect','خ-ل-و → خَلَا',
               [('دَعَا','root د-ع-و','he called'),('رَمَى','root ر-م-ي','he threw')]),
    '2:14:10': ('فَيَاعِيل','Broken plural','Devils — broken plural of شَيْطَان','ش-ط-ن → شَيَاطِين',
                [('مَيَادِين','root م-ي-د','plazas'),('عَجَائِب','root ع-ج-ب','wonders')]),
    '2:14:11': ('فَعَلَ','Form I perfect verb (hollow)','They said — base perfect','ق-و-ل → قَالَ',
                [('كَانَ','root ك-و-ن','he was'),('زَادَ','root ز-ي-د','he increased')]),
    '2:14:16': ('مُسْتَفْعِل','Form X active participle','Mockers — ones who seek to mock','ه-ز-أ → مُسْتَهْزِئ',
                [('مُسْتَغْفِر','root غ-ف-ر','one who seeks forgiveness'),('مُسْتَعِين','root ع-و-ن','one who seeks aid')]),
    # ── 2:15 ──────────────────────────────────────────────────────────────
    '2:15:1': ('-','Proper noun','The divine name Allāh — no derivational pattern','—',[]),
    '2:15:2': ('يَسْتَفْعِلُ','Form X imperfect verb','He mocks — seeking-form imperfect','ه-ز-أ → يَسْتَهْزِئُ',
               [('يَسْتَغْفِرُ','root غ-ف-ر','he seeks forgiveness'),('يَسْتَعِينُ','root ع-و-ن','he seeks aid')]),
    '2:15:4': ('يَفْعُلُ','Form I imperfect verb (geminate)','He extends — base imperfect','م-د-د → يَمُدُّ',
               [('يَرُدُّ','root ر-د-د','he repels'),('يَفُكُّ','root ف-ك-ك','he unties')]),
    '2:15:6': ('-','Verbal noun (مصدر)','Transgression — action noun; weak-root form فُعْلَان, hand-verified','—',[]),
    '2:15:7': ('يَفْعَلُ','Form I imperfect verb','They wander blindly — base imperfect','ع-م-ه → يَعْمَهُ',
               [('يَكْتُبُ','root ك-ت-ب','he writes'),('يَفْتَحُ','root ف-ت-ح','he opens')]),
    # ── 2:16 ──────────────────────────────────────────────────────────────
    '2:16:3': ('اِفْتَعَلَ','Form VIII perfect verb','They bought — acquired-form perfect','ش-ر-ي → اشْتَرَى',
               [('اِفْتَتَحَ','root ف-ت-ح','he opened'),('اِجْتَمَعَ','root ج-م-ع','he gathered')]),
    '2:16:4': ('فَعَالَة','Form I noun','Error, going astray — noun of the concept','ض-ل-ل → ضَلَالَة',
               [('جَهَالَة','root ج-ه-ل','ignorance'),('سَفَاهَة','root س-ف-ه','foolishness')]),
    '2:16:5': ('فُعْلَى','Weak verbal noun','Guidance — noun of quality from a defective root','ه-د-ي → هُدًى',
               [('مُدًى','root م-د-ي','extent'),('هُدًى','root ه-د-ي','guidance')]),
    '2:16:7': ('فَعِلَ','Form I perfect verb (kasra)','It profited — base perfect','ر-ب-ح → رَبِحَ',
               [('سَمِعَ','root س-م-ع','he heard'),('عَلِمَ','root ع-ل-م','he knew')]),
    '2:16:8': ('فِعَالَة','Form I noun','Commerce — noun of the trade','ت-ج-ر → تِجَارَة',
               [('كِتَابَة','root ك-ت-ب','writing'),('عِبَادَة','root ع-ب-د','worship')]),
    '2:16:10': ('فَعَلَ','Form I perfect verb (hollow)','They were — base perfect of being','ك-و-ن → كَانَ',
                [('قَالَ','root ق-و-ل','he said'),('زَادَ','root ز-ي-د','he increased')]),
    '2:16:11': ('مُفْتَعِل','Form VIII active participle','Guided ones — those who acquire guidance','ه-د-ي → مُهْتَدٍ',
                [('مُكْتَسِب','root ك-س-ب','one who earns'),('مُجْتَهِد','root ج-ه-د','one who strives')]),
    # ── 2:17 ──────────────────────────────────────────────────────────────
    '2:17:1': ('فَعَل','Form I noun','Example, similitude — basic noun','م-ث-ل → مَثَل',
               [('جَمَل','root ج-م-ل','camel'),('شَرَف','root ش-ر-ف','honor')]),
    '2:17:2': ('فَعَل','Form I noun','Example, similitude — basic noun','م-ث-ل → مَثَل',
               [('جَمَل','root ج-م-ل','camel'),('شَرَف','root ش-ر-ف','honor')]),
    '2:17:4': ('اِسْتَفْعَلَ','Form X perfect verb','He kindled — seeking-form perfect','و-ق-د → اسْتَوْقَدَ',
               [('اِسْتَغْفَرَ','root غ-ف-ر','he sought forgiveness'),('اِسْتَعَانَ','root ع-و-ن','he sought aid')]),
    '2:17:7': ('أَفْعَلَ','Form IV perfect verb','It illuminated — causative perfect','ض-و-أ → أَضَاءَ',
               [('أَنْزَلَ','root ن-ز-ل','he sent down'),('أَكْرَمَ','root ك-ر-م','he honored')]),
    '2:17:9': ('فَعْل','Form I noun','Around, surroundings — basic noun','ح-و-ل → حَوْل',
               [('قَوْل','root ق-و-ل','saying'),('مَوْت','root م-و-ت','death')]),
    '2:17:5': ('-','Form I noun (weak root)','Fire — pattern فَعَل per dominant analysis (نَوَر → نَار); classical sources also cite نَيْر — kept as verified-null pending scholarly confirmation','—',[]),
    '2:17:10': ('فَعَلَ','Form I perfect verb','He went — base perfect','ذ-ه-ب → ذَهَبَ',
                [('كَتَبَ','root ك-ت-ب','he wrote'),('جَلَسَ','root ج-ل-س','he sat')]),
    '2:17:11': ('-','Proper noun','The divine name Allāh — no derivational pattern','—',[]),
    '2:17:12': ('فُعْل','Form I noun','Light — basic noun','ن-و-ر → نُور',
                [('قُفْل','root ق-ف-ل','lock'),('جُنْد','root ج-ن-د','army')]),
    '2:17:13': ('فَعَلَ','Form I perfect verb','He left — base perfect','ت-ر-ك → تَرَكَ',
                [('كَتَبَ','root ك-ت-ب','he wrote'),('جَلَسَ','root ج-ل-س','he sat')]),
    '2:17:15': ('فُعُلَات','Broken plural','Darknesses — broken plural of ظُلْمَة','ظ-ل-م → ظُلُمَات',
                [('غُرُفَات','root غ-ر-ف','rooms'),('حُجُرَات','root ح-ج-ر','chambers')]),
    '2:17:17': ('يُفْعِلُ','Form IV imperfect verb','They see — causative imperfect','ب-ص-ر → يُبْصِرُ',
                [('يُكْرِمُ','root ك-ر-م','he honors'),('يُعْلِمُ','root ع-ل-م','he informs')]),
    # ── 2:18 ──────────────────────────────────────────────────────────────
    '2:18:1': ('فُعْل','Broken plural','Deaf ones — plural of أَصَمّ','ص-م-م → صُمّ',
               [('حُمْر','root ح-م-ر','red ones'),('سُود','root س-و-د','black ones')]),
    '2:18:2': ('فُعْل','Broken plural','Mute ones — plural of أَبْكَم','ب-ك-م → بُكْم',
               [('حُمْر','root ح-م-ر','red ones'),('سُود','root س-و-د','black ones')]),
    '2:18:3': ('فُعْل','Broken plural','Blind ones — plural of أَعْمَى','ع-م-ي → عُمْي',
               [('حُمْر','root ح-م-ر','red ones'),('سُود','root س-و-د','black ones')]),
    '2:18:6': ('يَفْعِلُ','Form I imperfect verb (kasra)','They return — base imperfect','ر-ج-ع → يَرْجِعُ',
               [('يَضْرِبُ','root ض-ر-ب','he strikes'),('يَجْلِسُ','root ج-ل-س','he sits')]),
    # ── 2:19 ──────────────────────────────────────────────────────────────
    '2:19:2': ('فَيْعِل','Form I adjective','Heavy rain (downpour) — intensive adjective','ص-و-ب → صَيِّب',
               [('سَيِّد','root س-و-د','master'),('مَيْت','root م-و-ت','dead')]),
    '2:19:4': ('فَعَال','Form I noun','Sky, heaven — basic noun','س-م-و → سَمَاء',
               [('جَمَال','root ج-م-ل','beauty'),('سَلَام','root س-ل-م','peace')]),
    '2:19:6': ('فُعُلَات','Broken plural','Darknesses — broken plural of ظُلْمَة','ظ-ل-م → ظُلُمَات',
               [('غُرُفَات','root غ-ر-ف','rooms'),('حُجُرَات','root ح-ج-ر','chambers')]),
    '2:19:7': ('فَعْل','Form I noun','Thunder — basic noun','ر-ع-د → رَعْد',
               [('بَرْق','root ب-ر-ق','lightning'),('فَجْر','root ف-ج-ر','dawn')]),
    '2:19:8': ('فَعْل','Form I noun','Lightning — basic noun','ب-ر-ق → بَرْق',
               [('رَعْد','root ر-ع-د','thunder'),('فَجْر','root ف-ج-ر','dawn')]),
    '2:19:9': ('يَفْعَلُ','Form I imperfect verb','They place, make — base imperfect','ج-ع-ل → يَجْعَلُ',
               [('يَكْتُبُ','root ك-ت-ب','he writes'),('يَفْتَحُ','root ف-ت-ح','he opens')]),
    '2:19:10': ('أَفَاعِل','Broken plural','Fingers — broken plural of إِصْبَع','ص-ب-ع → أَصَابِع',
                [('أَنَامِل','root ن-م-ل','fingertips'),('أَبَاطِل','root ب-ط-ل','falsehoods')]),
    '2:19:12': ('أَفْعَال','Broken plural','Ears — broken plural of أُذُن','أ-ذ-ن → آذَان',
                [('أَفْوَاه','root ف-و-ه','mouths'),('أَعْمَال','root ع-م-ل','deeds')]),
    '2:19:14': ('فَوَاعِل','Broken plural','Lightning bolts — broken plural of صَاعِقَة','ص-ع-ق → صَوَاعِق',
                [('كَوَاكِب','root ك-و-ك-ب','planets'),('جَوَارِح','root ج-ر-ح','birds of prey')]),
    '2:19:15': ('-','Verbal noun (مصدر)','Fear, caution — action noun; فَعَل pattern, hand-verified','—',[]),
    '2:19:16': ('فَعْل','Form I noun','Death — basic noun','م-و-ت → مَوْت',
                [('قَوْل','root ق-و-ل','saying'),('حَوْل','root ح-و-ل','around')]),
    '2:19:17': ('-','Proper noun','The divine name Allāh — no derivational pattern','—',[]),
    '2:19:18': ('مُفْعِل','Form IV active participle','Encompassing — causative doer','ح-و-ط → مُحِيط',
                [('مُكْرِم','root ك-ر-م','one who honors'),('مُحْسِن','root ح-س-ن','one who does good')]),
    '2:19:19': ('فَاعِل','Form I active participle','The disbelievers — active doers','ك-ف-ر → كَافِر',
                [('كَاتِب','root ك-ت-ب','writer'),('ظَالِم','root ظ-ل-م','wrongdoer')]),
    # ── 2:20 ──────────────────────────────────────────────────────────────
    '2:20:1': ('يَفْعَلُ','Form I imperfect verb (hollow)','He almost — near-auxiliary verb','ك-و-د → يَكَادُ',
               [('يَقُولُ','root ق-و-ل','he says'),('يَكُونُ','root ك-و-ن','he is')]),
    '2:20:2': ('فَعْل','Form I noun','Lightning — basic noun','ب-ر-ق → بَرْق',
               [('رَعْد','root ر-ع-د','thunder'),('فَجْر','root ف-ج-ر','dawn')]),
    '2:20:3': ('يَفْعَلُ','Form I imperfect verb','He snatches — base imperfect','خ-ط-ف → يَخْطَفُ',
               [('يَعْلَمُ','root ع-ل-م','he knows'),('يَسْمَعُ','root س-م-ع','he hears')]),
    '2:20:4': ('أَفْعَال','Broken plural','Sights — broken plural of بَصَر','ب-ص-ر → أَبْصَار',
               [('أَفْوَاه','root ف-و-ه','mouths'),('أَعْمَال','root ع-م-ل','deeds')]),
    '2:20:6': ('أَفْعَلَ','Form IV perfect verb','It shone — causative perfect','ض-و-أ → أَضَاءَ',
               [('أَنْزَلَ','root ن-ز-ل','he sent down'),('أَكْرَمَ','root ك-ر-م','he honored')]),
    '2:20:8': ('فَعَلَ','Form I perfect verb (defective)','They walked — base perfect','م-ش-ي → مَشَى',
               [('رَمَى','root ر-م-ي','he threw'),('سَعَى','root س-ع-ي','he strived')]),
    '2:20:11': ('أَفْعَلَ','Form IV perfect verb','It darkened — causative perfect','ظ-ل-م → أَظْلَمَ',
                [('أَنْزَلَ','root ن-ز-ل','he sent down'),('أَكْرَمَ','root ك-ر-م','he honored')]),
    '2:20:13': ('فَعَلَ','Form I perfect verb (hollow)','They stood — base perfect','ق-و-م → قَامَ',
                [('كَانَ','root ك-و-ن','he was'),('قَالَ','root ق-و-ل','he said')]),
    '2:20:15': ('فَعَلَ','Form I perfect verb (defective)','He willed — base perfect','ش-ي-أ → شَاءَ',
                [('جَاءَ','root ج-ي-أ','he came'),('سَاءَ','root س-و-أ','it was bad')]),
    '2:20:16': ('-','Proper noun','The divine name Allāh — no derivational pattern','—',[]),
    '2:20:21': ('-','Proper noun','The divine name Allāh — no derivational pattern','—',[]),
    '2:20:5': ('-','Compound particle','Whenever — compound of كُلّ (all) + مَا; no derivational pattern','—',[]),
    '2:20:17': ('فَعَلَ','Form I perfect verb','He would have gone — base perfect','ذ-ه-ب → ذَهَبَ',
                [('كَتَبَ','root ك-ت-ب','he wrote'),('جَلَسَ','root ج-ل-س','he sat')]),
    '2:20:18': ('فَعْل','Form I verbal noun','Hearing — base noun','س-م-ع → سَمْع',
                [('عَقْل','root ع-ق-ل','intellect'),('عِلْم','root ع-ل-م','knowledge')]),
    '2:20:19': ('أَفْعَال','Broken plural','Sights — broken plural of بَصَر','ب-ص-ر → أَبْصَار',
                [('أَفْوَاه','root ف-و-ه','mouths'),('أَعْمَال','root ع-م-ل','deeds')]),
    '2:20:23': ('-','Noun of totality','All, every — a unique noun with no derivational pattern','—',[]),
    '2:20:24': ('فَعْل','Form I noun','Thing — basic noun','ش-ي-أ → شَيْء',
                [('سَيْف','root س-ي-ف','sword'),('بَيْت','root ب-ي-ت','house')]),
    '2:20:25': ('فَعِيل','Form I adjective (intensive)','Able, powerful — intensive adjective','ق-د-ر → قَدِير',
                [('عَلِيم','root ع-ل-م','all-knowing'),('حَكِيم','root ح-ك-م','wise')]),
}